/**
 * Auto-generated User path mapping
 * DO NOT EDIT MANUALLY - Generated by scripts/generate-schema.ts
 */

export interface PathMap {
  [path: string]: {
    field: string;
    children?: string[];
  };
}

export const UserPathMap: PathMap = {
  "custom.balance.number": {
    field: "balanceNumber",
  },
  "custom.balance.mode": {
    field: "balanceMode",
  },
  "custom.balance.solid": {
    field: "balanceSolid",
  },
  "custom.balance.url": {
    field: "balanceUrl",
  },
  "custom.profile.bio": {
    field: "profileBio",
  },
  "custom.profile.mode": {
    field: "profileMode",
  },
  "custom.profile.solid": {
    field: "profileSolid",
  },
  "custom.profile.url": {
    field: "profileUrl",
  },
  "custom.profile.color": {
    field: "profileColor",
  },
  "custom.profile.icons": {
    field: "profileIcons",
  },
  "custom.profile.icons_padding": {
    field: "profileIconsPadding",
  },
  "custom.rank.mode": {
    field: "rankMode",
  },
  "custom.rank.solid": {
    field: "rankSolid",
  },
  "custom.rank.url": {
    field: "rankUrl",
  },
  "custom.rank.color": {
    field: "rankColor",
  },
  "custom.level_up.mode": {
    field: "levelupMode",
  },
  "custom.level_up.solid": {
    field: "levelupSolid",
  },
  "custom.level_up.url": {
    field: "levelupUrl",
  },
  "custom.badges": {
    field: "customBadges",
  },
  "temp.games": {
    field: "tempGames",
  },
  "temp.voice_time": {
    field: "tempVoiceTime",
  },
  "presets.jtc": {
    field: "jtcPresets",
  },
  custom: {
    field: "",
    children: ["badges", "balance", "level_up", "profile", "rank"],
  },
  "custom.balance": {
    field: "",
    children: ["mode", "number", "solid", "url"],
  },
  "custom.profile": {
    field: "",
    children: ["bio", "color", "icons", "icons_padding", "mode", "solid", "url"],
  },
  "custom.rank": {
    field: "",
    children: ["color", "mode", "solid", "url"],
  },
  "custom.level_up": {
    field: "",
    children: ["mode", "solid", "url"],
  },
  temp: {
    field: "",
    children: ["games", "voice_time"],
  },
  presets: {
    field: "",
    children: ["jtc"],
  },
};

// Note: MongoDB paths () are not included in FieldMap
export const UserFieldMap: Record<string, string> = {
  "custom.balance.number": "balanceNumber",
  "custom.balance.mode": "balanceMode",
  "custom.balance.solid": "balanceSolid",
  "custom.balance.url": "balanceUrl",
  "custom.profile.bio": "profileBio",
  "custom.profile.mode": "profileMode",
  "custom.profile.solid": "profileSolid",
  "custom.profile.url": "profileUrl",
  "custom.profile.color": "profileColor",
  "custom.profile.icons": "profileIcons",
  "custom.profile.icons_padding": "profileIconsPadding",
  "custom.rank.mode": "rankMode",
  "custom.rank.solid": "rankSolid",
  "custom.rank.url": "rankUrl",
  "custom.rank.color": "rankColor",
  "custom.level_up.mode": "levelupMode",
  "custom.level_up.solid": "levelupSolid",
  "custom.level_up.url": "levelupUrl",
  "custom.badges": "customBadges",
  "temp.games": "tempGames",
  "temp.voice_time": "tempVoiceTime",
  "presets.jtc": "jtcPresets",
};
